# Generated by Django 3.2.8 on 2021-10-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='My username', max_length=15)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('stock', models.IntegerField()),
                ('unitary_price', models.DecimalField(decimal_places=3, max_digits=11)),
                ('description', models.TextField(verbose_name=500)),
            ],
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ssacgApp.users')),
            ],
            options={
                'abstract': False,
            },
            bases=('ssacgApp.users',),
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ssacgApp.users')),
                ('address', models.CharField(max_length=30, null=True, verbose_name='Shipping address')),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ssacgApp.users',),
        ),
        migrations.CreateModel(
            name='Orders_detail',
            fields=[
                ('id_order_detail', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.IntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=3, max_digits=11)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='ssacgApp.orders')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_products', to='ssacgApp.products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Administrator', to='ssacgApp.admins'),
        ),
    ]
