# Generated by Django 3.2.8 on 2021-10-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_client', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, null=True, verbose_name='Clients name')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Cient sign up email')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('address', models.CharField(max_length=30, verbose_name='Shipping address')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Client phone number')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
