# Generated by Django 3.2.8 on 2021-10-11 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssacgApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_detail',
            name='id_order',
        ),
        migrations.RemoveField(
            model_name='orders_detail',
            name='id_product',
        ),
        migrations.AddField(
            model_name='orders_detail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_detail', to='ssacgApp.orders'),
        ),
        migrations.AddField(
            model_name='orders_detail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_products', to='ssacgApp.products'),
        ),
    ]
