# Generated by Django 3.2.8 on 2021-10-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssacgApp', '0002_auto_20211011_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_product_log',
            fields=[
                ('id_product_log', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation', models.CharField(default='r', max_length=1, verbose_name='CRUD operation type')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_log_admin', to='ssacgApp.admins')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_admin_log', to='ssacgApp.products')),
            ],
        ),
    ]
