# Generated by Django 3.2.8 on 2021-10-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssacgApp', '0003_admin_product_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='admin',
        ),
    ]
