# Generated by Django 3.2.8 on 2021-10-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssacgApp', '0004_remove_products_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
