# Generated by Django 3.2.8 on 2021-10-25 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssacgApp', '0006_auto_20211018_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='invalid stock input')]),
        ),
        migrations.AlterField(
            model_name='products',
            name='unitary_price',
            field=models.DecimalField(decimal_places=3, max_digits=11, validators=[django.core.validators.MinValueValidator(0.001, message='invalid price input')]),
        ),
    ]
