# Generated by Django 3.2.8 on 2021-10-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssacgApp', '0009_products_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img_src',
            field=models.CharField(default='Sin imágen', max_length=65534),
        ),
    ]
