from .clientSerializer import ClientSerializer
from .adminSerializer import AdminSerializer
from .productsSerializer import ProductsSerializer
from .orders_detailSerializer import Orders_detailSerializer